name: Deploy Docs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (default: dev)'
        default: 'dev'

jobs: 
  build:
    env:
      RAT_URL: "https://rascalsoftware.github.io/RAT/"
      RAT_VERSION: "${{ github.event.inputs.version }}"
    runs-on: Linux

    steps:
    - uses: actions/checkout@v4      
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    - name: Download MATLAB RAT
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if [ ${RAT_VERSION} == 'dev' ]; then
          wget https://github.com/RascalSoftware/RAT/releases/download/nightly/Linux.zip
          pip install RATapi
        else
          wget "https://github.com/RascalSoftware/RAT/releases/download/${RAT_VERSION}/Linux.zip"
          pip install RATapi==${RAT_VERSION}
        fi
        unzip Linux.zip -d API/
        python build_docs.py
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        repository: RascalSoftware/RAT
        ref: gh-pages
        path: _web
        token: ${{ secrets.DOCS_DEPLOY_TOKEN }}
    - name: Deploy docs
      if: github.ref == 'refs/heads/main'
      run: |
        python deploy.py
        cd _web
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "Publish Documentation" || true
        git push
